
-- Restore the missing kitchen_appliances category
INSERT INTO public.categories (id, name, emoji, is_paid, sort_order)
VALUES ('kitchen_appliances', 'Kitchen Tools', '🍳', true, 6)
ON CONFLICT (id) DO NOTHING;

-- Insert 300 kitchen tool/appliance words
INSERT INTO public.words (text, category) VALUES
('Aeropress', 'kitchen_appliances'),
('Air Fryer', 'kitchen_appliances'),
('Appam Maker', 'kitchen_appliances'),
('Apple Corer', 'kitchen_appliances'),
('Apron', 'kitchen_appliances'),
('Avocado Tool', 'kitchen_appliances'),
('Bagel Slicer', 'kitchen_appliances'),
('Baking Sheet', 'kitchen_appliances'),
('Balloon Whisk', 'kitchen_appliances'),
('Bamboo Paddle', 'kitchen_appliances'),
('Bamboo Steamer', 'kitchen_appliances'),
('Banana Slicer', 'kitchen_appliances'),
('Bar Spoon', 'kitchen_appliances'),
('Basting Brush', 'kitchen_appliances'),
('Basting Mop', 'kitchen_appliances'),
('Bean Slicer', 'kitchen_appliances'),
('Bench Scraper', 'kitchen_appliances'),
('Berry Huller', 'kitchen_appliances'),
('Biscuit Cutter', 'kitchen_appliances'),
('Blender', 'kitchen_appliances'),
('Blow Torch', 'kitchen_appliances'),
('Bottle Opener', 'kitchen_appliances'),
('Bouillon Strainer', 'kitchen_appliances'),
('Bowl Scraper', 'kitchen_appliances'),
('Box Grater', 'kitchen_appliances'),
('Bread Board', 'kitchen_appliances'),
('Bread Knife', 'kitchen_appliances'),
('Bread Machine', 'kitchen_appliances'),
('Bread Pan', 'kitchen_appliances'),
('Broiler Pan', 'kitchen_appliances'),
('Brownie Pan', 'kitchen_appliances'),
('Bundt Pan', 'kitchen_appliances'),
('Burger Press', 'kitchen_appliances'),
('Butter Curler', 'kitchen_appliances'),
('Butter Dish', 'kitchen_appliances'),
('Butter Knife', 'kitchen_appliances'),
('Butter Mold', 'kitchen_appliances'),
('Cake Leveler', 'kitchen_appliances'),
('Cake Pan', 'kitchen_appliances'),
('Cake Stand', 'kitchen_appliances'),
('Cake Tester', 'kitchen_appliances'),
('Can Opener', 'kitchen_appliances'),
('Candy Mold', 'kitchen_appliances'),
('Candy Thermometer', 'kitchen_appliances'),
('Canning Jar', 'kitchen_appliances'),
('Carafe', 'kitchen_appliances'),
('Carving Fork', 'kitchen_appliances'),
('Carving Knife', 'kitchen_appliances'),
('Casserole Dish', 'kitchen_appliances'),
('Cast Iron Pan', 'kitchen_appliances'),
('Ceramic Knife', 'kitchen_appliances'),
('Champagne Flute', 'kitchen_appliances'),
('Chapati Press', 'kitchen_appliances'),
('Cheese Board', 'kitchen_appliances'),
('Cheese Grater', 'kitchen_appliances'),
('Cheese Knife', 'kitchen_appliances'),
('Cheese Slicer', 'kitchen_appliances'),
('Cherry Pitter', 'kitchen_appliances'),
('Chimney Starter', 'kitchen_appliances'),
('China Cap', 'kitchen_appliances'),
('Chinois', 'kitchen_appliances'),
('Chip Pan', 'kitchen_appliances'),
('Chopping Board', 'kitchen_appliances'),
('Churner', 'kitchen_appliances'),
('Citrus Juicer', 'kitchen_appliances'),
('Citrus Reamer', 'kitchen_appliances'),
('Citrus Zester', 'kitchen_appliances'),
('Cleaver', 'kitchen_appliances'),
('Cocktail Shaker', 'kitchen_appliances'),
('Cocotte', 'kitchen_appliances'),
('Coffee Grinder', 'kitchen_appliances'),
('Coffee Maker', 'kitchen_appliances'),
('Coffee Press', 'kitchen_appliances'),
('Colander', 'kitchen_appliances'),
('Condiment Dispenser', 'kitchen_appliances'),
('Cookie Cutter', 'kitchen_appliances'),
('Cookie Press', 'kitchen_appliances'),
('Cookie Sheet', 'kitchen_appliances'),
('Cooling Rack', 'kitchen_appliances'),
('Copper Pan', 'kitchen_appliances'),
('Corkscrew', 'kitchen_appliances'),
('Corn Holder', 'kitchen_appliances'),
('Corn Stripper', 'kitchen_appliances'),
('Couscousier', 'kitchen_appliances'),
('Crepe Pan', 'kitchen_appliances'),
('Cupcake Tin', 'kitchen_appliances'),
('Cutting Board', 'kitchen_appliances'),
('Dariole Mold', 'kitchen_appliances'),
('Dehydrator', 'kitchen_appliances'),
('Deli Slicer', 'kitchen_appliances'),
('Digital Scale', 'kitchen_appliances'),
('Dish Rack', 'kitchen_appliances'),
('Dishwasher', 'kitchen_appliances'),
('Dough Docker', 'kitchen_appliances'),
('Dough Hook', 'kitchen_appliances'),
('Dough Scraper', 'kitchen_appliances'),
('Double Boiler', 'kitchen_appliances'),
('Dumpling Maker', 'kitchen_appliances'),
('Dumpling Mold', 'kitchen_appliances'),
('Dutch Oven', 'kitchen_appliances'),
('Egg Beater', 'kitchen_appliances'),
('Egg Coddler', 'kitchen_appliances'),
('Egg Cup', 'kitchen_appliances'),
('Egg Poacher', 'kitchen_appliances'),
('Egg Ring', 'kitchen_appliances'),
('Egg Separator', 'kitchen_appliances'),
('Egg Slicer', 'kitchen_appliances'),
('Egg Timer', 'kitchen_appliances'),
('Electric Grill', 'kitchen_appliances'),
('Electric Kettle', 'kitchen_appliances'),
('Escargot Dish', 'kitchen_appliances'),
('Espresso Machine', 'kitchen_appliances'),
('Falafel Scoop', 'kitchen_appliances'),
('Fat Separator', 'kitchen_appliances'),
('Filleting Knife', 'kitchen_appliances'),
('Fine Mesh Sieve', 'kitchen_appliances'),
('Fish Scaler', 'kitchen_appliances'),
('Fish Spatula', 'kitchen_appliances'),
('Flame Tamer', 'kitchen_appliances'),
('Flan Ring', 'kitchen_appliances'),
('Flat Whisk', 'kitchen_appliances'),
('Flour Duster', 'kitchen_appliances'),
('Flour Sifter', 'kitchen_appliances'),
('Focaccia Pan', 'kitchen_appliances'),
('Fondue Pot', 'kitchen_appliances'),
('Food Mill', 'kitchen_appliances'),
('Food Processor', 'kitchen_appliances'),
('Food Steamer', 'kitchen_appliances'),
('Freezer', 'kitchen_appliances'),
('French Press', 'kitchen_appliances'),
('Fridge', 'kitchen_appliances'),
('Frying Pan', 'kitchen_appliances'),
('Funnel', 'kitchen_appliances'),
('Garlic Press', 'kitchen_appliances'),
('Garnish Kit', 'kitchen_appliances'),
('Gelato Maker', 'kitchen_appliances'),
('Ginger Grater', 'kitchen_appliances'),
('Glass Bowl', 'kitchen_appliances'),
('Grain Mill', 'kitchen_appliances'),
('Grapefruit Knife', 'kitchen_appliances'),
('Gratin Dish', 'kitchen_appliances'),
('Gravy Boat', 'kitchen_appliances'),
('Gravy Strainer', 'kitchen_appliances'),
('Griddle', 'kitchen_appliances'),
('Grill Basket', 'kitchen_appliances'),
('Grill Pan', 'kitchen_appliances'),
('Grill Tongs', 'kitchen_appliances'),
('Grinder', 'kitchen_appliances'),
('Gyuto Knife', 'kitchen_appliances'),
('Hand Mixer', 'kitchen_appliances'),
('Herb Mill', 'kitchen_appliances'),
('Herb Scissors', 'kitchen_appliances'),
('Herb Stripper', 'kitchen_appliances'),
('Honey Dipper', 'kitchen_appliances'),
('Honey Pot', 'kitchen_appliances'),
('Hot Plate', 'kitchen_appliances'),
('Ice Bucket', 'kitchen_appliances'),
('Ice Cream Maker', 'kitchen_appliances'),
('Ice Cream Scoop', 'kitchen_appliances'),
('Ice Mold', 'kitchen_appliances'),
('Ice Pick', 'kitchen_appliances'),
('Ice Tongs', 'kitchen_appliances'),
('Immersion Blender', 'kitchen_appliances'),
('Instant Pot', 'kitchen_appliances'),
('Jelly Bag', 'kitchen_appliances'),
('Jigger', 'kitchen_appliances'),
('Julienne Peeler', 'kitchen_appliances'),
('Juicer', 'kitchen_appliances'),
('Kebab Skewer', 'kitchen_appliances'),
('Kettle', 'kitchen_appliances'),
('Kitchen Scale', 'kitchen_appliances'),
('Kitchen Shears', 'kitchen_appliances'),
('Kitchen Timer', 'kitchen_appliances'),
('Kitchen Torch', 'kitchen_appliances'),
('Kitchen Twine', 'kitchen_appliances'),
('Kneading Board', 'kitchen_appliances'),
('Knife Block', 'kitchen_appliances'),
('Knife Sharpener', 'kitchen_appliances'),
('Ladle', 'kitchen_appliances'),
('Lame', 'kitchen_appliances'),
('Larding Needle', 'kitchen_appliances'),
('Lasagna Pan', 'kitchen_appliances'),
('Lemon Squeezer', 'kitchen_appliances'),
('Loaf Pan', 'kitchen_appliances'),
('Lobster Cracker', 'kitchen_appliances'),
('Lobster Pick', 'kitchen_appliances'),
('Lunchbox', 'kitchen_appliances'),
('Madeleine Pan', 'kitchen_appliances'),
('Mandoline', 'kitchen_appliances'),
('Mango Slicer', 'kitchen_appliances'),
('Marinade Injector', 'kitchen_appliances'),
('Masher', 'kitchen_appliances'),
('Matcha Whisk', 'kitchen_appliances'),
('Measuring Cup', 'kitchen_appliances'),
('Measuring Jug', 'kitchen_appliances'),
('Measuring Spoon', 'kitchen_appliances'),
('Meat Grinder', 'kitchen_appliances'),
('Meat Mallet', 'kitchen_appliances'),
('Meat Probe', 'kitchen_appliances'),
('Meat Tenderizer', 'kitchen_appliances'),
('Meat Thermometer', 'kitchen_appliances'),
('Melon Baller', 'kitchen_appliances'),
('Microplane', 'kitchen_appliances'),
('Microwave', 'kitchen_appliances'),
('Milk Frother', 'kitchen_appliances'),
('Milk Pan', 'kitchen_appliances'),
('Mini Chopper', 'kitchen_appliances'),
('Mixing Bowl', 'kitchen_appliances'),
('Molinillo', 'kitchen_appliances'),
('Molcajete', 'kitchen_appliances'),
('Mortar and Pestle', 'kitchen_appliances'),
('Mozzarella Slicer', 'kitchen_appliances'),
('Muffin Tin', 'kitchen_appliances'),
('Muddler', 'kitchen_appliances'),
('Mushroom Brush', 'kitchen_appliances'),
('Nakiri Knife', 'kitchen_appliances'),
('Nut Cracker', 'kitchen_appliances'),
('Nut Milk Bag', 'kitchen_appliances'),
('Offset Spatula', 'kitchen_appliances'),
('Omelet Pan', 'kitchen_appliances'),
('Onion Goggles', 'kitchen_appliances'),
('Oven Mitt', 'kitchen_appliances'),
('Oven Rack', 'kitchen_appliances'),
('Oven Thermometer', 'kitchen_appliances'),
('Oyster Knife', 'kitchen_appliances'),
('Paella Pan', 'kitchen_appliances'),
('Palette Knife', 'kitchen_appliances'),
('Panini Press', 'kitchen_appliances'),
('Parchment Paper', 'kitchen_appliances'),
('Paring Knife', 'kitchen_appliances'),
('Pasta Machine', 'kitchen_appliances'),
('Pasta Server', 'kitchen_appliances'),
('Pasta Spoon', 'kitchen_appliances'),
('Pastry Bag', 'kitchen_appliances'),
('Pastry Blender', 'kitchen_appliances'),
('Pastry Brush', 'kitchen_appliances'),
('Pastry Wheel', 'kitchen_appliances'),
('Peel', 'kitchen_appliances'),
('Peeler', 'kitchen_appliances'),
('Pepper Mill', 'kitchen_appliances'),
('Percolator', 'kitchen_appliances'),
('Pie Dish', 'kitchen_appliances'),
('Pie Server', 'kitchen_appliances'),
('Pie Weights', 'kitchen_appliances'),
('Pineapple Corer', 'kitchen_appliances'),
('Piping Nozzle', 'kitchen_appliances'),
('Piping Tip', 'kitchen_appliances'),
('Pizza Cutter', 'kitchen_appliances'),
('Pizza Peel', 'kitchen_appliances'),
('Pizza Stone', 'kitchen_appliances'),
('Platter', 'kitchen_appliances'),
('Popcorn Maker', 'kitchen_appliances'),
('Pot Holder', 'kitchen_appliances'),
('Pot Rack', 'kitchen_appliances'),
('Potato Masher', 'kitchen_appliances'),
('Potato Ricer', 'kitchen_appliances'),
('Pressure Cooker', 'kitchen_appliances'),
('Proofing Basket', 'kitchen_appliances'),
('Pudding Basin', 'kitchen_appliances'),
('Punch Bowl', 'kitchen_appliances'),
('Quiche Pan', 'kitchen_appliances'),
('Raclette Grill', 'kitchen_appliances'),
('Ramekin', 'kitchen_appliances'),
('Ravioli Cutter', 'kitchen_appliances'),
('Ravioli Mold', 'kitchen_appliances'),
('Rice Cooker', 'kitchen_appliances'),
('Rice Paddle', 'kitchen_appliances'),
('Ring Mold', 'kitchen_appliances'),
('Rivet Pan', 'kitchen_appliances'),
('Roasting Pan', 'kitchen_appliances'),
('Roasting Rack', 'kitchen_appliances'),
('Rocking Knife', 'kitchen_appliances'),
('Rolling Pin', 'kitchen_appliances'),
('Rotary Grater', 'kitchen_appliances'),
('Roti Press', 'kitchen_appliances'),
('Rubber Spatula', 'kitchen_appliances'),
('Salad Bowl', 'kitchen_appliances'),
('Salad Spinner', 'kitchen_appliances'),
('Salad Tongs', 'kitchen_appliances'),
('Salt Cellar', 'kitchen_appliances'),
('Salt Mill', 'kitchen_appliances'),
('Santoku Knife', 'kitchen_appliances'),
('Sauce Pan', 'kitchen_appliances'),
('Sausage Stuffer', 'kitchen_appliances'),
('Saute Pan', 'kitchen_appliances'),
('Savarin Mold', 'kitchen_appliances'),
('Scissors', 'kitchen_appliances'),
('Scoop', 'kitchen_appliances'),
('Scouring Pad', 'kitchen_appliances'),
('Seafood Fork', 'kitchen_appliances'),
('Serving Bowl', 'kitchen_appliances'),
('Serving Tray', 'kitchen_appliances'),
('Silicone Mat', 'kitchen_appliances'),
('Silicone Mold', 'kitchen_appliances'),
('Skillet', 'kitchen_appliances'),
('Skimmer', 'kitchen_appliances'),
('Slotted Spoon', 'kitchen_appliances'),
('Slow Cooker', 'kitchen_appliances'),
('Smoker Box', 'kitchen_appliances'),
('Smoothie Maker', 'kitchen_appliances'),
('Snail Tongs', 'kitchen_appliances'),
('Souffle Dish', 'kitchen_appliances'),
('Sous Vide', 'kitchen_appliances'),
('Spaetzle Maker', 'kitchen_appliances'),
('Spaghetti Measure', 'kitchen_appliances'),
('Spatula', 'kitchen_appliances'),
('Spice Grinder', 'kitchen_appliances'),
('Spice Rack', 'kitchen_appliances'),
('Spider Strainer', 'kitchen_appliances'),
('Spiralizer', 'kitchen_appliances'),
('Splatter Guard', 'kitchen_appliances'),
('Springform Pan', 'kitchen_appliances'),
('Squeeze Bottle', 'kitchen_appliances'),
('Stand Mixer', 'kitchen_appliances'),
('Steamer Basket', 'kitchen_appliances'),
('Steel Wool', 'kitchen_appliances'),
('Stew Pot', 'kitchen_appliances'),
('Stock Pot', 'kitchen_appliances'),
('Strainer', 'kitchen_appliances'),
('Strawberry Huller', 'kitchen_appliances'),
('Sugar Shaker', 'kitchen_appliances'),
('Sugar Thermometer', 'kitchen_appliances'),
('Sushi Mat', 'kitchen_appliances'),
('Sushi Knife', 'kitchen_appliances'),
('Tagine', 'kitchen_appliances'),
('Tamis', 'kitchen_appliances'),
('Tart Pan', 'kitchen_appliances'),
('Tea Infuser', 'kitchen_appliances'),
('Tea Kettle', 'kitchen_appliances'),
('Tea Strainer', 'kitchen_appliances'),
('Teapot', 'kitchen_appliances'),
('Terracotta Pot', 'kitchen_appliances'),
('Thermometer', 'kitchen_appliances'),
('Timer', 'kitchen_appliances'),
('Toaster', 'kitchen_appliances'),
('Toaster Oven', 'kitchen_appliances'),
('Tomato Slicer', 'kitchen_appliances'),
('Tongs', 'kitchen_appliances'),
('Tortilla Press', 'kitchen_appliances'),
('Trivet', 'kitchen_appliances'),
('Truffle Shaver', 'kitchen_appliances'),
('Tube Pan', 'kitchen_appliances'),
('Tuna Press', 'kitchen_appliances'),
('Turkey Baster', 'kitchen_appliances'),
('Turner', 'kitchen_appliances'),
('Utility Knife', 'kitchen_appliances'),
('Vacuum Sealer', 'kitchen_appliances'),
('Vegetable Brush', 'kitchen_appliances'),
('Vegetable Peeler', 'kitchen_appliances'),
('Waffle Iron', 'kitchen_appliances'),
('Water Filter', 'kitchen_appliances'),
('Whisk', 'kitchen_appliances'),
('Wine Opener', 'kitchen_appliances'),
('Wine Stopper', 'kitchen_appliances'),
('Wok', 'kitchen_appliances'),
('Wok Ring', 'kitchen_appliances'),
('Wooden Spoon', 'kitchen_appliances'),
('Yogurt Maker', 'kitchen_appliances'),
('Zester', 'kitchen_appliances')
ON CONFLICT DO NOTHING;
